insert_or_update_message('lblANWBMembershipInfo.Group0', 'en_GB', 'We collect your ANWB membership number to authenticate the people who wish to register on our site, and offer them special ANWB rates.');
insert_or_update_message('lblMobileNumberInfo.Group0', 'en_GB', 'We collect your mobile phone number for Interactive Voice Response (IVR to start & stop your parking session by placing a call), and sending SMS text reminders should you opt to receive them (extra fee).');
insert_or_update_message('lblBusinessNameInfo.Group0', 'en_GB', 'We collect your company name for invoicing & tax purposes.');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'en_GB', 'We collect your registration number with the Chamber of Commerce for invoicing & tax purposes.');
insert_or_update_message('lblVatNumberInfo.Group0', 'en_GB', 'We collect your VAT-number for invoicing & tax purposes.');
insert_or_update_message('lblGenderInfo.Group0', 'en_GB', 'We collect your gender for customer relationship management (salutation: Mr / Mrs), and for debt collection purposes should there be an invoice you fail to settle, and we need to share this information with the Debt Collection Agency following our 'Reminder Process'.');
insert_or_update_message('lblFirstnameInfo.Group0', 'en_GB', 'We collect your first name for invoicing & tax purposes, shipping via postal service, and customer relationship management to authenticate caller when you call our Customer Service Desk.');
insert_or_update_message('lblLastnameInfo.Group0', 'en_GB', 'We collect your last name for invoicing & tax purposes, shipping via postal service, and customer relationship management to authenticate caller when you call our Customer Service Desk.');
insert_or_update_message('lblDateofbirthInfo.Group0', 'en_GB', 'We collect your date of birth for debt collection purposes should there be an invoice you fail to settle, and we need to share this information with the Debt Collection Agency following our 'Reminder Process'.');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'en_GB', 'We collect your landline phone number for customer relationship management when our Customer Service Desk representative contacts you.');
insert_or_update_message('lblEmailInfo.Group0', 'en_GB', 'We collect your email address for customer relationship management (customer queries, invoice claims, technical update information, and marketing newsletters if you opt in).');
insert_or_update_message('lblAddressInfo.Group0', 'en_GB', 'Billing Address: we collect your home address for invoicing & tax purposes, the address to which your invoice will be issued.');
insert_or_update_message('lblPostalAddressInfo.Group0', 'en_GB', 'Shipping & Mailing Addresses: we collect your postal address for invoicing & tax purposes, this is the address to which your shipment will be delivered via postal service.');
insert_or_update_message('lblBASC', 'en_GB', 'Basic');
insert_or_update_message('lblFLEX', 'en_GB', 'Flex');
insert_or_update_message('lblSUBC', 'en_GB', 'Unlimited');
insert_or_update_message('lblMyPlan', 'en_GB', 'My Plan');
insert_or_update_message('lblFixedTransactionFee', 'en_GB', 'Fixed transaction fee');
insert_or_update_message('lblChangePlan', 'en_GB', 'Change plan');
insert_or_update_message('lblWeeklySubscriptionFee', 'en_GB', 'Weekly subscription fee');
insert_or_update_message('lblChoose', 'en_GB', 'Choose');
insert_or_update_message('lblCancelTill', 'en_GB', 'You can cancel your order till {0}, <span>{1}</span>');
insert_or_update_message('lblCancelPlanChangeRequest', 'en_GB', 'Cancel order');
insert_or_update_message('lblPlanChangeSucceded', 'en_GB', 'Your subscription plan was changed successfully.');
insert_or_update_message('lblPlanChangeCanceled', 'en_GB', 'Your request for subscription plan change was canceled successfully.');
insert_or_update_message('lblMinimumTransactionFee', 'en_GB', 'Minimum transaction fee');
insert_or_update_message('lblMaximumTransactionFee', 'en_GB', 'Maximum transaction fee');
insert_or_update_message('lblFirstPPlusPassIsFree', 'en_GB', '1e P+ pass free');
insert_or_update_message('searchTransactions.showOpenTransactions', 'en_GB', 'Open transactions');
insert_or_update_message('lblMyPlanDescription', 'en_GB', 'With Yellowbrick you can choose three plans:<br>Flex, Basic and Unlimited.');
insert_or_update_message('lblPlanChangeCancelFailed', 'en_GB', 'The canceling has failed.');
insert_or_update_message('lblMonday', 'en_GB', 'Monday');
insert_or_update_message('lblTuesday', 'en_GB', 'Tuesday');
insert_or_update_message('lblWednesday', 'en_GB', 'Wednesday');
insert_or_update_message('lblThursday', 'en_GB', 'Thursday');
insert_or_update_message('lblFriday', 'en_GB', 'Friday');
insert_or_update_message('lblSaturday', 'en_GB', 'Saturday');
insert_or_update_message('lblSunday', 'en_GB', 'Sunday');
insert_or_update_message('flatPricingPerUnit', 'en_GB', 'Per transaction');
insert_or_update_message('subscriptionPricingPerUnit', 'en_GB', 'Per week per user');
insert_or_update_message('labelContact', 'en_GB', 'Contact');
insert_or_update_message('flexPricingPerUnit', 'en_GB', 'Per transaction from');


insert_or_update_message('lblANWBMembershipInfo.Group0', 'nl_NL', 'Uw lidmaatschapsnummer slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblMobileNumberInfo.Group0', 'nl_NL', 'Uw mobiele nummer slaan we op om SMS-reminders te versturen indien u dit aanvraagd');
insert_or_update_message('lblBusinessNameInfo.Group0', 'nl_NL', 'Uw bedrijfsnaam slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'nl_NL', 'Uw KvK-nummer slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblVatNumberInfo.Group0', 'nl_NL', 'Uw BTW-identificatienummer slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblGenderInfo.Group0', 'nl_NL', 'Uw geslacht slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblFirstnameInfo.Group0', 'nl_NL', 'Uw voornaam slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblLastnameInfo.Group0', 'nl_NL', 'Uw achternaam slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblDateofbirthInfo.Group0', 'nl_NL', 'Uw geboortedatum slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'nl_NL', 'Uw telefoonnummer slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblEmailInfo.Group0', 'nl_NL', 'Uw e-mailadres slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblAddressInfo.Group0', 'nl_NL', 'Uw adres slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblPostalAddressInfo.Group0', 'nl_NL', 'Uw postadres slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblBASC', 'nl_NL', 'Basic');
insert_or_update_message('lblFLEX', 'nl_NL', 'Flex');
insert_or_update_message('lblSUBC', 'nl_NL', 'Unlimited');
insert_or_update_message('lblMyPlan', 'nl_NL', 'Mijn abonnement');
insert_or_update_message('lblFixedTransactionFee', 'nl_NL', 'Vaste transactiekosten');
insert_or_update_message('lblChangePlan', 'nl_NL', 'Wijzig abonnement');
insert_or_update_message('lblWeeklySubscriptionFee', 'nl_NL', 'Wekelijkse abonnementskosten');
insert_or_update_message('lblChoose', 'nl_NL', 'Kies');
insert_or_update_message('lblCancelTill', 'nl_NL', 'Annuleer bestelling tot {0}, <span>{1}</span>');
insert_or_update_message('lblCancelPlanChangeRequest', 'nl_NL', 'Annuleer bestelling');
insert_or_update_message('lblPlanChangeSucceded', 'nl_NL', 'Je abonnement is succesvol gewijzigd');
insert_or_update_message('lblPlanChangeCanceled', 'nl_NL', 'Je verzoek tot wijzigen van abonnement is succesvol geannuleerd');
insert_or_update_message('lblMinimumTransactionFee', 'nl_NL', 'Minimale transactiekosten');
insert_or_update_message('lblMaximumTransactionFee', 'nl_NL', 'Maximale transactiekosten');
insert_or_update_message('lblFirstPPlusPassIsFree', 'nl_NL', '1e P+ Pas gratis');
insert_or_update_message('searchTransactions.showOpenTransactions', 'nl_NL', 'Open transacties');
insert_or_update_message('lblMyPlanDescription', 'nl_NL', 'Met Yellowbrick heb je de keuze uit Flex, Basic en Unlimited');
insert_or_update_message('lblPlanChangeCancelFailed', 'nl_NL', 'De annulering is niet voltooid');
insert_or_update_message('lblMonday', 'nl_NL', 'Maandag');
insert_or_update_message('lblTuesday', 'nl_NL', 'Dinsdag');
insert_or_update_message('lblWednesday', 'nl_NL', 'Woensdag');
insert_or_update_message('lblThursday', 'nl_NL', 'Donderdag');
insert_or_update_message('lblFriday', 'nl_NL', 'Vrijdag');
insert_or_update_message('lblSaturday', 'nl_NL', 'Zaterdag');
insert_or_update_message('lblSunday', 'nl_NL', 'Zondag');
insert_or_update_message('flatPricingPerUnit', 'nl_NL', 'Per transactie');
insert_or_update_message('subscriptionPricingPerUnit', 'nl_NL', 'Per week per gebruiker');
insert_or_update_message('labelContact', 'nl_NL', 'Contact');
insert_or_update_message('flexPricingPerUnit', 'nl_NL', 'Per transactie vanaf');


