insert_or_update_message('lblMobileNumberInfo.Group0', 'en_GB', 'We collect your mobile phone number for Interactive Voice Response (IVR to start & stop your parking session by placing a call), and sending SMS text reminders should you opt to receive them (extra fee).');
insert_or_update_message('lblBusinessNameInfo.Group0', 'en_GB', 'We collect your company name for invoicing & tax purposes.');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'en_GB', 'We collect your registration number with the Chamber of Commerce for invoicing & tax purposes.');
insert_or_update_message('lblVatNumberInfo.Group0', 'en_GB', 'We collect your VAT-number for invoicing & tax purposes.');
insert_or_update_message('lblGenderInfo.Group0', 'en_GB', 'We collect your gender for customer relationship management (salutation: Mr / Mrs), and for debt collection purposes should there be an invoice you fail to settle, and we need to share this information with the Debt Collection Agency following our 'Reminder Process'.');
insert_or_update_message('lblFirstnameInfo.Group0', 'en_GB', 'We collect your first name for invoicing & tax purposes, shipping via postal service, and customer relationship management to authenticate caller when you call our Customer Service Desk.');
insert_or_update_message('lblLastnameInfo.Group0', 'en_GB', 'We collect your last name for invoicing & tax purposes, shipping via postal service, and customer relationship management to authenticate caller when you call our Customer Service Desk.');
insert_or_update_message('lblDateofbirthInfo.Group0', 'en_GB', 'We collect your date of birth for debt collection purposes should there be an invoice you fail to settle, and we need to share this information with the Debt Collection Agency following our 'Reminder Process'.');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'en_GB', 'We collect your landline phone number for customer relationship management when our Customer Service Desk representative contacts you.');
insert_or_update_message('lblEmailInfo.Group0', 'en_GB', 'We collect your email address for customer relationship management (customer queries, invoice claims, technical update information, and marketing newsletters if you opt in).');
insert_or_update_message('lblAddressInfo.Group0', 'en_GB', 'Billing Address: we collect your home address for invoicing & tax purposes, the address to which your invoice will be issued.');
insert_or_update_message('lblPostalAddressInfo.Group0', 'en_GB', 'Shipping & Mailing Addresses: we collect your postal address for invoicing & tax purposes, this is the address to which your shipment will be delivered via postal service.');
insert_or_update_message('lblBASC', 'en_GB', 'Basic');
insert_or_update_message('lblFLEX', 'en_GB', 'Flex');
insert_or_update_message('lblSUBC', 'en_GB', 'Unlimited');
insert_or_update_message('lblMyPlan', 'en_GB', 'My Plan');
insert_or_update_message('lblFixedTransactionFee', 'en_GB', 'Fixed transaction fee');
insert_or_update_message('lblChangePlan', 'en_GB', 'Change plan');
insert_or_update_message('lblWeeklySubscriptionFee', 'en_GB', 'Weekly subscription fee');
insert_or_update_message('lblChoose', 'en_GB', 'Choose');
insert_or_update_message('lblCancelTill', 'en_GB', 'You can cancel your order till {0}, <span>{1}</span>');
insert_or_update_message('lblCancelPlanChangeRequest', 'en_GB', 'Cancel order');
insert_or_update_message('lblPlanChangeSucceded', 'en_GB', 'Your subscription plan was changed successfully.');
insert_or_update_message('lblPlanChangeCanceled', 'en_GB', 'Your request for subscription plan change was canceled successfully.');
insert_or_update_message('lblMinimumTransactionFee', 'en_GB', 'Minimum transaction fee');
insert_or_update_message('lblMaximumTransactionFee', 'en_GB', 'Maximum transaction fee');
insert_or_update_message('searchTransactions.showOpenTransactions', 'en_GB', 'Open transactions');
insert_or_update_message('lblMyPlanDescription', 'en_GB', 'With Yellowbrick you can choose three plans:<br>Flex, Basic and Unlimited.');
insert_or_update_message('lblPlanChangeCancelFailed', 'en_GB', 'The canceling has failed.');
insert_or_update_message('lblMonday', 'en_GB', 'Monday');
insert_or_update_message('lblTuesday', 'en_GB', 'Tuesday');
insert_or_update_message('lblWednesday', 'en_GB', 'Wednesday');
insert_or_update_message('lblThursday', 'en_GB', 'Thursday');
insert_or_update_message('lblFriday', 'en_GB', 'Friday');
insert_or_update_message('lblSaturday', 'en_GB', 'Saturday');
insert_or_update_message('lblSunday', 'en_GB', 'Sunday');
insert_or_update_message('flatPricingPerUnit', 'en_GB', 'Per transaction');
insert_or_update_message('subscriptionPricingPerUnit', 'en_GB', 'Per week per user');
insert_or_update_message('labelContact', 'en_GB', 'Contact');
insert_or_update_message('flexPricingPerUnit', 'en_GB', 'Per transaction from');


insert_or_update_message('lblMobileNumberInfo.Group0', 'nl_BE', 'Uw mobiele nummer slaan we op om SMS-reminders te versturen indien u dit aanvraagd');
insert_or_update_message('lblBusinessNameInfo.Group0', 'nl_BE', 'Uw bedrijfsnaam slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'nl_BE', 'Uw KvK-nummer slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblVatNumberInfo.Group0', 'nl_BE', 'Uw BTW-identificatienummer slaan we op ten behoeve van uw administratie');
insert_or_update_message('lblGenderInfo.Group0', 'nl_BE', 'Uw geslacht slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblFirstnameInfo.Group0', 'nl_BE', 'Uw voornaam slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblLastnameInfo.Group0', 'nl_BE', 'Uw achternaam slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblDateofbirthInfo.Group0', 'nl_BE', 'Uw geboortedatum slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'nl_BE', 'Uw telefoonnummer slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblEmailInfo.Group0', 'nl_BE', 'Uw e-mailadres slaan wij op ten behoeve van onze klantenservice');
insert_or_update_message('lblAddressInfo.Group0', 'nl_BE', 'Uw adres slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblPostalAddressInfo.Group0', 'nl_BE', 'Uw postadres slaan wij op ten behoeve van onze administratie');
insert_or_update_message('lblBASC', 'nl_BE', 'Basic');
insert_or_update_message('lblFLEX', 'nl_BE', 'Flex');
insert_or_update_message('lblSUBC', 'nl_BE', 'Unlimited');
insert_or_update_message('lblMyPlan', 'nl_BE', 'Mijn abonnement');
insert_or_update_message('lblFixedTransactionFee', 'nl_BE', 'Vaste transactiekosten');
insert_or_update_message('lblChangePlan', 'nl_BE', 'Wijzig abonnement');
insert_or_update_message('lblWeeklySubscriptionFee', 'nl_BE', 'Wekelijkse abonnementskosten');
insert_or_update_message('lblChoose', 'nl_BE', 'Kies');
insert_or_update_message('lblCancelTill', 'nl_BE', 'Annuleer bestelling tot');
insert_or_update_message('lblCancelPlanChangeRequest', 'nl_BE', 'Annuleer bestelling');
insert_or_update_message('lblPlanChangeSucceded', 'nl_BE', 'Je abonnement is succesvol gewijzigd');
insert_or_update_message('lblPlanChangeCanceled', 'nl_BE', 'Je verzoek tot wijzigen van abonnement is succesvol geannuleerd');
insert_or_update_message('lblMinimumTransactionFee', 'nl_BE', 'Minimale transactiekosten');
insert_or_update_message('lblMaximumTransactionFee', 'nl_BE', 'Maximale transactiekosten');
insert_or_update_message('searchTransactions.showOpenTransactions', 'nl_BE', 'Open transacties');
insert_or_update_message('lblMyPlanDescription', 'nl_BE', 'Met Yellowbrick heb je de keuze uit Flex, Basic en Unlimited');
insert_or_update_message('lblPlanChangeCancelFailed', 'nl_BE', 'De annulering is niet voltooid');
insert_or_update_message('lblMonday', 'nl_BE', 'Maandag');
insert_or_update_message('lblTuesday', 'nl_BE', 'Dinsdag');
insert_or_update_message('lblWednesday', 'nl_BE', 'Woensdag');
insert_or_update_message('lblThursday', 'nl_BE', 'Donderdag');
insert_or_update_message('lblFriday', 'nl_BE', 'Vrijdag');
insert_or_update_message('lblSaturday', 'nl_BE', 'Zaterdag');
insert_or_update_message('lblSunday', 'nl_BE', 'Zondag');
insert_or_update_message('flatPricingPerUnit', 'nl_BE', 'Per transactie');
insert_or_update_message('subscriptionPricingPerUnit', 'nl_BE', 'Per week per gebruiker');
insert_or_update_message('labelContact', 'nl_BE', 'Contact');
insert_or_update_message('flexPricingPerUnit', 'nl_BE', 'Per transactie vanaf');


insert_or_update_message('lblMobileNumberInfo.Group0', 'fr_BE', 'Nous avons besoin de votre numéro de téléphone portable pour envoyer des rappels par SMS si nécessaire');
insert_or_update_message('lblBusinessNameInfo.Group0', 'fr_BE', 'Pour des raisons administratives nous avons besoin du nom de votre entreprise.');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'fr_BE', 'Pour des raisons administratives nous avons besoin de votre numéro d&#39;entreprise.');
insert_or_update_message('lblVatNumberInfo.Group0', 'fr_BE', 'Pour des raisons administratives nous avons besoin de votre numéro de T.V.A.');
insert_or_update_message('lblGenderInfo.Group0', 'fr_BE', 'Dans le cadre des échanges avec notre service à la clientèle, nous avons besoin de connaître votre sexe.');
insert_or_update_message('lblFirstnameInfo.Group0', 'fr_BE', 'Dans le cadre des échanges avec notre service à la clientèle, nous avons besoin de connaître votre prénom.');
insert_or_update_message('lblLastnameInfo.Group0', 'fr_BE', 'Dans le cadre des échanges avec notre service à la clientèle, nous avons besoin de connaître votre nom.');
insert_or_update_message('lblDateofbirthInfo.Group0', 'fr_BE', 'Dans le cadre des échanges avec notre service à la clientèle, nous avons besoin de connaître votre date de naissance.');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'fr_BE', 'Dans le cadre des échanges avec notre service à la clientèle, nous avons besoin de connaître votre numéro de téléphone.');
insert_or_update_message('lblEmailInfo.Group0', 'fr_BE', 'Dans le cadre des échanges avec notre service à la clientèle, nous avons besoin de connaître votre adresse e-mail.');
insert_or_update_message('lblAddressInfo.Group0', 'fr_BE', 'Pour des raisons administratives nous avons besoin de votre adresse.');
insert_or_update_message('lblPostalAddressInfo.Group0', 'fr_BE', 'Pour des raisons administratives nous avons besoin de votre adresse postale.');
insert_or_update_message('lblBASC', 'fr_BE', 'Basic');
insert_or_update_message('lblFLEX', 'fr_BE', 'Flex');
insert_or_update_message('lblSUBC', 'fr_BE', 'Unlimited');
insert_or_update_message('lblMyPlan', 'fr_BE', 'Mon plan tarifaire');
insert_or_update_message('lblFixedTransactionFee', 'fr_BE', 'Frais de transactions fixes');
insert_or_update_message('lblChangePlan', 'fr_BE', 'Changer mon plan tarifaire');
insert_or_update_message('lblWeeklySubscriptionFee', 'fr_BE', 'Abonnement hebdomadaire');
insert_or_update_message('lblChoose', 'fr_BE', 'Choisir');
insert_or_update_message('lblCancelTill', 'fr_BE', 'Vous pouvez modifier votre choix jusqu&#39;au {0}, <span>{1}</span>');
insert_or_update_message('lblCancelPlanChangeRequest', 'fr_BE', 'Annuler');
insert_or_update_message('lblPlanChangeSucceded', 'fr_BE', 'Votre abonnement a été modifié avec succès');
insert_or_update_message('lblPlanChangeCanceled', 'fr_BE', 'Votre demande de changement de plan tarifaire a été modifié avec succès.');
insert_or_update_message('lblMinimumTransactionFee', 'fr_BE', 'Frais de transaction minimum');
insert_or_update_message('lblMaximumTransactionFee', 'fr_BE', 'Frais de transaction maximal');
insert_or_update_message('searchTransactions.showOpenTransactions', 'fr_BE', 'Transactions en cours');
insert_or_update_message('lblMyPlanDescription', 'fr_BE', 'Avec Yellowbrick vous avez le choix entre trois plans tarifaires: <br>Flex, Basic et Unlimited.');
insert_or_update_message('lblPlanChangeCancelFailed', 'fr_BE', 'L&#39;annulation a échoué.');
insert_or_update_message('lblMonday', 'fr_BE', 'Lundi');
insert_or_update_message('lblTuesday', 'fr_BE', 'Mardi');
insert_or_update_message('lblWednesday', 'fr_BE', 'Mercredi');
insert_or_update_message('lblThursday', 'fr_BE', 'Jeudi');
insert_or_update_message('lblFriday', 'fr_BE', 'Vendredi');
insert_or_update_message('lblSaturday', 'fr_BE', 'Samedi');
insert_or_update_message('lblSunday', 'fr_BE', 'Dimanche');
insert_or_update_message('flatPricingPerUnit', 'fr_BE', 'Par transaction');
insert_or_update_message('subscriptionPricingPerUnit', 'fr_BE', 'Par semaine par utilisateur');
insert_or_update_message('labelContact', 'fr_BE', 'Contact');
insert_or_update_message('flexPricingPerUnit', 'fr_BE', 'Par transaction à partir de');


