insert_or_update_message('lblMobileNumberInfo.Group0', 'en_GB', 'We need your mobile phone number for sending text-reminders should you require to receive them');
insert_or_update_message('lblBusinessNameInfo.Group0', 'en_GB', 'We need/save your company name for your administration ');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'en_GB', 'We need/save your registration number with the Chamber of Commerce for your administration.');
insert_or_update_message('lblVatNumberInfo.Group0', 'en_GB', 'We need/save your VAT-number for your administration ');
insert_or_update_message('lblGenderInfo.Group0', 'en_GB', 'We save your gender for the purpose of our customer service');
insert_or_update_message('lblFirstnameInfo.Group0', 'en_GB', 'We save your first name for the purpose of our administration');
insert_or_update_message('lblLastnameInfo.Group0', 'en_GB', 'We save your last name for the purpose of our administration');
insert_or_update_message('lblDateofbirthInfo.Group0', 'en_GB', 'We save your date of birth for the purpose of our customer service');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'en_GB', 'We save your phone number for the purpose of our customer service');
insert_or_update_message('lblEmailInfo.Group0', 'en_GB', 'We save your email address for the purpose of our customer service');
insert_or_update_message('lblAddressInfo.Group0', 'en_GB', 'We save your address for the purpose of our administration');
insert_or_update_message('lblPostalAddressInfo.Group0', 'en_GB', 'We save your postal address for the purpose of our administration');
insert_or_update_message('lblBASC', 'en_GB', 'Basic');
insert_or_update_message('lblFLEX', 'en_GB', 'Flex');
insert_or_update_message('lblSUBC', 'en_GB', 'Unlimited');
insert_or_update_message('lblMyPlan', 'en_GB', 'My Plan');
insert_or_update_message('lblFixedTransactionFee', 'en_GB', 'Fixed transaction fee');
insert_or_update_message('lblChangePlan', 'en_GB', 'Change plan');
insert_or_update_message('lblWeeklySubscriptionFee', 'en_GB', 'Weekly subscription fee');
insert_or_update_message('lblChoose', 'en_GB', 'Choose');
insert_or_update_message('lblCancelTill', 'en_GB', 'You can cancel your order till {0}, <span>{1}</span>');
insert_or_update_message('lblCancelPlanChangeRequest', 'en_GB', 'Cancel order');
insert_or_update_message('lblPlanChangeSucceded', 'en_GB', 'Your subscription plan was changed successfully.');
insert_or_update_message('lblPlanChangeCanceled', 'en_GB', 'Your request for subscription plan change was canceled successfully.');
insert_or_update_message('lblMinimumTransactionFee', 'en_GB', 'Minimum transaction fee');
insert_or_update_message('lblMaximumTransactionFee', 'en_GB', 'Maximum transaction fee');
insert_or_update_message('searchTransactions.showOpenTransactions', 'en_GB', 'Open transactions');
insert_or_update_message('lblMyPlanDescription', 'en_GB', 'With Yellowbrick you can choose three plans:<br>Flex, Basic and Unlimited.');
insert_or_update_message('lblPlanChangeCancelFailed', 'en_GB', 'The canceling has failed.');
insert_or_update_message('lblMonday', 'en_GB', 'Monday');
insert_or_update_message('lblTuesday', 'en_GB', 'Tuesday');
insert_or_update_message('lblWednesday', 'en_GB', 'Wednesday');
insert_or_update_message('lblThursday', 'en_GB', 'Thursday');
insert_or_update_message('lblFriday', 'en_GB', 'Friday');
insert_or_update_message('lblSaturday', 'en_GB', 'Saturday');
insert_or_update_message('lblSunday', 'en_GB', 'Sunday');
insert_or_update_message('flatPricingPerUnit', 'en_GB', 'Per transaction');
insert_or_update_message('subscriptionPricingPerUnit', 'en_GB', 'Per week per user');
insert_or_update_message('labelContact', 'en_GB', 'Contact');
insert_or_update_message('flexPricingPerUnit', 'en_GB', 'Per transaction from');


insert_or_update_message('lblMobileNumberInfo.Group0', 'de_DE', 'Wir benötigen Ihre Mobilfunknummer, um Ihnen Erinnerungen per Text-Nachricht zu schicken');
insert_or_update_message('lblBusinessNameInfo.Group0', 'de_DE', 'Wir benötigen und speichern Ihren Firmennamen für Ihre korrekte Administration und Rechnungsausstellung');
insert_or_update_message('lblBusinessRegistrationNumberInfo.Group0', 'de_DE', 'Wir benötigen und speichern Ihre Registrierung bei der Handyelskammer für Ihre Verwaltung');
insert_or_update_message('lblVatNumberInfo.Group0', 'de_DE', 'Wir benötigen und speichern Ihre Steuer-Nr. für die korrekte Administration und Rechnungsausstellung');
insert_or_update_message('lblGenderInfo.Group0', 'de_DE', 'Wir speichern Ihr Geschlecht, damit unser Kundenservice Sie korrekt ansprechen kann.');
insert_or_update_message('lblFirstnameInfo.Group0', 'de_DE', 'Wir speichern Ihren Vornamen für unsere interne Administration');
insert_or_update_message('lblLastnameInfo.Group0', 'de_DE', 'Wir speichern Ihren Nachnamen für unsere interne Administration');
insert_or_update_message('lblDateofbirthInfo.Group0', 'de_DE', 'Wir speichern Ihr Geburtsdatum, damit unser Kundenservice Sie schneller finden kann');
insert_or_update_message('lblToolkitPhoneInfo.Group0', 'de_DE', 'Wir speichern Ihre Mobilfunknummer, damit unser Kundenservice Sie schneller finden kann');
insert_or_update_message('lblEmailInfo.Group0', 'de_DE', 'Wir speichern Ihre E-Mail Adresse, damit unser Kundenservice Ihnen bspw. Ihre Rechnung zusenden kann');
insert_or_update_message('lblAddressInfo.Group0', 'de_DE', 'Wir speichern Ihre Adresse für unsere interne Administration');
insert_or_update_message('lblPostalAddressInfo.Group0', 'de_DE', 'Wir speichern Ihre Postanschrift, damit wir Ihnen Ihre Rechnung korrekt ausstellen können');
insert_or_update_message('lblBASC', 'de_DE', 'Basic');
insert_or_update_message('lblFLEX', 'de_DE', 'Flex');
insert_or_update_message('lblSUBC', 'de_DE', 'Unbegrenzt');
insert_or_update_message('lblMyPlan', 'de_DE', 'Mein Plan');
insert_or_update_message('lblFixedTransactionFee', 'de_DE', 'Fixe Transaktionsgebühr');
insert_or_update_message('lblChangePlan', 'de_DE', 'Tarif ändern');
insert_or_update_message('lblWeeklySubscriptionFee', 'de_DE', 'Wöchentliche Gebühr');
insert_or_update_message('lblChoose', 'de_DE', 'Auswählen');
insert_or_update_message('lblCancelTill', 'de_DE', 'Stornierung möglich bis {0}, <span>{1}</span>');
insert_or_update_message('lblCancelPlanChangeRequest', 'de_DE', 'Bestellung stornieren');
insert_or_update_message('lblPlanChangeSucceded', 'de_DE', 'Ihr PREMIUM Tarif Plan wurde erfolgreich geändert');
insert_or_update_message('lblPlanChangeCanceled', 'de_DE', 'Ihre Tarifänderung war erfolgreich');
insert_or_update_message('lblMinimumTransactionFee', 'de_DE', 'Min. Transaktionsgebühr');
insert_or_update_message('lblMaximumTransactionFee', 'de_DE', 'Max. Transaktionsgebühr');
insert_or_update_message('searchTransactions.showOpenTransactions', 'de_DE', 'Offene Transaktionen');
insert_or_update_message('lblMyPlanDescription', 'de_DE', 'Bei Yellowbrick können Sie aus 3 Tarifen den für Sie Passenden auswählen::<br>FLEX, BASE und PREMIUM.');
insert_or_update_message('lblPlanChangeCancelFailed', 'de_DE', 'Die Änderung hat leider nicht geklappt.');
insert_or_update_message('lblMonday', 'de_DE', 'Montag');
insert_or_update_message('lblTuesday', 'de_DE', 'Dienstag');
insert_or_update_message('lblWednesday', 'de_DE', 'Mittwoch');
insert_or_update_message('lblThursday', 'de_DE', 'Donnerstag');
insert_or_update_message('lblFriday', 'de_DE', 'Freitag');
insert_or_update_message('lblSaturday', 'de_DE', 'Samstag');
insert_or_update_message('lblSunday', 'de_DE', 'Sonntag');
insert_or_update_message('flatPricingPerUnit', 'de_DE', 'Pro transaktion');
insert_or_update_message('subscriptionPricingPerUnit', 'de_DE', 'Pro woche pro benutzer');
insert_or_update_message('labelContact', 'de_DE', 'Kontakt');
insert_or_update_message('flexPricingPerUnit', 'de_DE', 'Pro transaktion von');


